# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

# Ignore some builtin hints
- ignore: {name: Eta reduce}
- ignore: {name: Redundant multi-way if}
- ignore: {name: Use if}
