name: HLint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  hlint:
    name: HLint
    runs-on: ubuntu-latest
    permissions:
      # Needed to upload results to GitHub code scanning.
      security-events: write
    steps:
    - uses: actions/checkout@v4
    - name: Check code with hlint
      uses: haskell-actions/hlint-scan@v1
      with:
        # We are not scanning `test/` at the moment due to issues with `QuasiQuotes`
        path: src app Examples
        hints: .hlint.yaml
